---

DOCKER_ENVIRONMENT:
  # Application
  TYPO3_CONTEXT:   "{{ lookup('env','TYPO3_CONTEXT') }}"
  FLOW_CONTEXT:   "{{ lookup('env','FLOW_CONTEXT') }}"
  FLOW_REWRITEURLS: "{{ lookup('env','FLOW_REWRITEURLS') }}"

  SYMFONY_ENV:     "{{ lookup('env','SYMFONY_ENV') }}"
  SYMFONY_DEBUG:   "{{ lookup('env','SYMFONY_DEBUG') }}"

  CAKE_ENV:        "{{ lookup('env','CAKE_ENV') }}"

  YII_ENVIRONMENT: "{{ lookup('env','YII_ENVIRONMENT') }}"

  # General
  CLI_SCRIPT:          "{{ lookup('env','CLI_SCRIPT') }}"
  MAIL_GATEWAY:        "{{ lookup('env','MAIL_GATEWAY') }}"

  # MySQL
  MYSQL_ROOT_PASSWORD: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}"
  MYSQL_USER:          "{{ lookup('env','MYSQL_USER') }}"
  MYSQL_PASSWORD:      "{{ lookup('env','MYSQL_PASSWORD') }}"
  MYSQL_DATABASE:      "{{ lookup('env','MYSQL_DATABASE') }}"

  # Postgres
  POSTGRES_USER:       "{{ lookup('env','POSTGRES_USER') }}"
  POSTGRES_PASSWORD:   "{{ lookup('env','POSTGRES_PASSWORD') }}"

  # FTP
  FTP_USER:            "{{ lookup('env','FTP_USER') }}"
  FTP_PASSWORD:        "{{ lookup('env','FTP_PASSWORD') }}"
  FTP_PATH:            "{{ lookup('env','FTP_PATH') }}"
